// .vuepress/components/phylotree.vue
<template>
	<div className="App">
		<div id="value"></div>
	</div>
</template>

<script>

var _ = require("underscore");
var $ = window.$ = require("jquery");
import {Runtime, Inspector} from "@observablehq/notebook-runtime";
import notebook from "displaying-phylogenetic-trees-with-phylotree-js";

export default {
  mounted () {
    this.loadObservable();
  },
  methods: {
    loadObservable () {
			Runtime.load(notebook, (cell) => {
				if (cell.name == 'phylotree') {
					return new Inspector(document.getElementById("value"));
				}
			});
    }
  }
}

</script>

<style>
	@import '../../node_modules/phylotree/phylotree.css'
</style>

// src/lib/components/Phylotree.svelte
<script>
	import { onMount } from 'svelte';
	import { Runtime, Inspector } from '@observablehq/notebook-runtime';
	import notebook from 'displaying-phylogenetic-trees-with-phylotree-js';

	let container;

	onMount(() => {
		Runtime.load(notebook, (cell) => {
			if (cell.name == 'phylotree') {
				return new Inspector(container);
			}
		});
	});
</script>

<div class="phylotree-app">
	<div bind:this={container} id="value"></div>
</div>

<style>
	@import 'phylotree/phylotree.css';
</style>
